spring:
  application:
    name: couponservice
  mongodb:
    host: localhost
    port: 27017
    database: le_coupons
    username: user
    password: password
    authentication-database: admin
    auto-index-creation: true

grpc:
  server:
    port: 9091

server:
  port: 8081
